apiVersion: v1
kind: Service
metadata:
  name: wellspokn-frontend-service
spec:
  selector:
    app: wellspokn-frontend
  type: NodePort
  ports:
    - nodePort: 30000
      port: 5000
      protocol: TCP
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wellspokn-frontend
  labels:
    app: wellspokn-frontend
spec:
  selector:
    matchLabels:
      app: wellspokn-frontend
  template:
    metadata:
      labels:
        app: wellspokn-frontend
    spec:
      containers:
      - name: wellspokn-frontend
        image: wellspokn-frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 5000