apiVersion: apps/v1
kind: Deployment
metadata:
  name: wellspokn-backend
  labels:
    app: wellspokn-backend
spec:
  selector:
    matchLabels:
      app: wellspokn-backend
  template:
    metadata:
      labels:
        app: wellspokn-backend
    spec:
      containers:
      - name: wellspokn-backend
        image: wellspokn-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wellspokn-backend-service
spec:
  selector:
    app: wellspokn-backend
  type: NodePort
  ports:
    - nodePort: 30001
      port: 8080
      protocol: TCP
      targetPort: 8080